# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChuckNorryFacts' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'RxSwift', '6.1.0'
  pod 'RxCocoa', '6.1.0'
  pod 'SwiftLint'

  # Pods for ChuckNorryFacts

  target 'ChuckNorryFactsTests' do
    inherit! :search_paths
    pod 'RxBlocking', '6.1.0'
    pod 'RxTest', '6.1.0'
    
  end

  target 'ChuckNorryFactsUITests' do
    # Pods for testing
  end
  

end


